# Generated by Django 6.0.7 on 2026-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
