# Generated by Django 6.0.7 on 2026-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='exam_documents/'),
        ),
    ]
