# Generated by Django 6.0.7 on 2026-07-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('ESSAY', 'Essay'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill blank'), ('SHORT_ANSWER', 'Short answer'), ('MATCHING', 'Matching')], default='MCQ', max_length=20)),
                ('question', models.TextField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.exam')),
            ],
        ),
    ]
